"""empty message

Revision ID: 2396ba206279
Revises: 
Create Date: 2017-12-18 12:50:55.451799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2396ba206279'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tweets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet', sa.String(length=500), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('retweet', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('website', sa.String(length=80), nullable=True),
    sa.Column('profile_photo', sa.String(length=80), nullable=True),
    sa.Column('header_photo', sa.String(length=80), nullable=True),
    sa.Column('tweets', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('signup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['signup_id'], ['signup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.drop_table('tweets')
    op.drop_table('signup')
    # ### end Alembic commands ###
