"""empty message

Revision ID: 7bbb0304a35c
Revises: 7ae2dd0fb40f
Create Date: 2017-12-21 18:07:49.625538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bbb0304a35c'
down_revision = '7ae2dd0fb40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('date', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followers', 'date')
    # ### end Alembic commands ###
